name: 'Backend CI/CD 🚀'
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: 'Test 🔬'
    strategy:
      matrix:
        os: 
          - ubuntu-latest
        python-version:
          - "3.11"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # cache: 'pip'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run:  |
          conda env create -f kimchi.yml
          conda activate kimchi
      - name: Run tests
        run: |
           make test

